version: '3.4'
services:
  mysql-db:
    image: mysql:5.7.38
    platform: linux/x86_64
    volumes:
      - "../services/common/mysql_db:/docker-entrypoint-initdb.d"
      - mysql-data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-network

  chat-notification:
    image: chat-notification
    ports:
        - 1338:1338
    networks:
        - app-network
    depends_on:
        - mysql-db
        - redis
        - chat-socket
    environment:
      - DB_HOST=mysql-db
      - REDIS_HOST=redis
      - WEBSOCKET_HOST=chat-socket

  chat-socket:
    image: chat-socket:latest
    ports:
      - 1337:1337
    networks:
      - app-network
    environment:
     - DB_HOST=mysql-db
     - REDIS_HOST=redis
    depends_on:
      - mysql-db
      - redis

networks:
  app-network:
    name: app-network

volumes:
  mysql-data: